### ISSUE TITLE
Demo example

### ISSUE THREAD

**Issue by AlexDeltax** [pmaigutyak/mp-liqpay#2]
Have you full demo example of working app? 
I got `AttributeError: module 'liqpay' has no attribute 'get_checkout_form'`
Seems like I've missed something, but I can't figure out what.
Thanks for any help

**Comment by pmaigutyak** [comment]
Hi,
this is full app from my project
[payments.zip](https://github.com/pmaigutyak/mp-liqpay/files/2145247/payments.zip)

**Comment by pmaigutyak** [comment]
HTML form looks like this:
`<form action="{{ checkout_form.action }}" method="{{ checkout_form.method }}" target="_blank">`
`    {{ checkout_form }}`
`...`
`</form>`

**Comment by AlexDeltax** [comment]
Oh, thanks, now I see, what I have missed :sweat_smile:

**Comment by pmaigutyak** [comment]
Welcome!
